<a href="https://colab.research.google.com/github/shlomiye/Pytorch_Tutorial_Youtube/blob/main/Gradient_Calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.randn(3)

In [3]:
x

tensor([-0.2857, -1.3416, -0.7727])

In [4]:
x = torch.randn(3, requires_grad=True)

In [5]:
x

tensor([-1.5900, -1.1681,  0.4507], requires_grad=True)

In [6]:
y = x + 2

In [7]:
print(y)

tensor([0.4100, 0.8319, 2.4507], grad_fn=<AddBackward0>)


In [8]:
z = y*y*2

In [9]:
z

tensor([ 0.3363,  1.3840, 12.0116], grad_fn=<MulBackward0>)

In [10]:
z = z.mean()

In [11]:
z

tensor(4.5773, grad_fn=<MeanBackward0>)

In [12]:
z.backward() # dz/dx

In [13]:
print(x.grad)

tensor([0.5467, 1.1091, 3.2676])


In [14]:
# How to stop tracking the gradients

# 1. x.requires_grad_()
# 2. x.detach()
# 3. with torch.no_grad():

In [15]:
# example 1

x = torch.randn(3, requires_grad = True)

In [16]:
print(x)

tensor([0.5316, 2.3831, 0.2223], requires_grad=True)


In [17]:
x.requires_grad_(False)

tensor([0.5316, 2.3831, 0.2223])

In [18]:
# example 2

x = torch.randn(3, requires_grad = True)

In [19]:
print(x)

tensor([-0.6325,  1.3110, -0.3145], requires_grad=True)


In [20]:
y = x.detach()
y

tensor([-0.6325,  1.3110, -0.3145])

In [21]:
# example 3

x = torch.randn(3, requires_grad = True)

In [22]:
print(x)

tensor([ 1.2425,  0.4929, -1.5089], requires_grad=True)


In [23]:
y = x+2
print(y)

tensor([3.2425, 2.4929, 0.4911], grad_fn=<AddBackward0>)


In [24]:
with torch.no_grad():
    y = x+2
    print(y)


tensor([3.2425, 2.4929, 0.4911])


In [25]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  # weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
