<a href="https://colab.research.google.com/github/shlomiye/Pytorch_Tutorial_Youtube/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.empty(2,2,3)

In [3]:
x

tensor([[[-1.2470e-20,  4.5242e-41, -1.2470e-20],
         [ 4.5242e-41,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  1.4013e-45],
         [ 3.0829e-44,  1.4153e-42,  2.0615e-19]]])

In [4]:
x = torch.rand(2,2)

In [5]:
x

tensor([[0.2562, 0.6687],
        [0.2735, 0.6324]])

In [6]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.ones(3,3, dtype=torch.float16)

In [8]:
print(x.dtype)

torch.float16


In [9]:
print(x.size())

torch.Size([3, 3])


In [10]:
# Create a tensor from a list
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [11]:
import numpy as np

In [12]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [13]:
b = a.numpy()

In [14]:
type(b)

numpy.ndarray

In [15]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [16]:
# Both point to the same memory location
print(b)

[2. 2. 2. 2. 2.]


In [17]:
 a = np.ones(5)

In [18]:
print(a)

[1. 1. 1. 1. 1.]


In [19]:
b = torch.from_numpy(a)

In [20]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [21]:
a +=1

In [22]:
a

array([2., 2., 2., 2., 2.])

In [23]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [24]:
torch.cuda.is_available()

False