<a href="https://colab.research.google.com/github/shlomiye/Pytorch_Tutorial_Youtube/blob/main/tensot_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)

In [3]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# Reshape if we don't know th number of itemes using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Reshape if we don't know th number of itemes using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [19]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
# with reshape and view they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch6= my_torch5.reshape(2,5)
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [30]:
my_torch5[1] = 4141

In [31]:
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [32]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [33]:
# Slices

In [41]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Grab a spcific item
my_torch7[7]

tensor(7)

In [46]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [48]:
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [50]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])