<a href="https://colab.research.google.com/github/shlomiye/Pytorch_Tutorial_Youtube/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [8]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [14]:
# Subtraction Longhand
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [15]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [16]:
# Multiplication Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [18]:
# Devision
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Div Longhand
torch.div(tensor_b , tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [21]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [23]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [25]:
# Exponent / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [26]:
# Another way to run longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# Reassignment_
tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [28]:
tensor_a

tensor([1, 2, 3, 4])

In [29]:
tensor_b

tensor([5, 6, 7, 8])

In [33]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [34]:
tensor_a

tensor([ 6,  8, 10, 12])