<a href="https://colab.research.google.com/github/shlomiye/Pytorch_Tutorial_Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

Lists

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

Numpy

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.61537195, 0.91933825, 0.3977766 , 0.13770652],
       [0.96302946, 0.02894649, 0.21715093, 0.11045708],
       [0.09483695, 0.67789764, 0.38563959, 0.90833895]])

In [6]:
np1.dtype

dtype('float64')

In [11]:
tensor_2d = torch.randn(3,4)

In [12]:
tensor_2d

tensor([[-1.7634,  1.1047,  1.3037, -1.2457],
        [ 0.0797, -0.8233,  0.0531,  0.3630],
        [-0.7695,  0.4525,  0.5340, -0.2970]])

In [13]:
tensor_3d = torch.zeros(2,3,4)

In [14]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
## Create tensor out of numpy array

In [16]:
my_tensor = torch.tensor(np1)

In [17]:
my_tensor

tensor([[0.6154, 0.9193, 0.3978, 0.1377],
        [0.9630, 0.0289, 0.2172, 0.1105],
        [0.0948, 0.6779, 0.3856, 0.9083]], dtype=torch.float64)